export { default as IconAdd } from './IconAdd.vue'
export { default as IconDelete } from './IconDelete.vue'
export { default as IconEdit } from './IconEdit.vue'
export { default as IconHeart } from './IconHeart.vue'
export { default as IconCalendar } from './IconCalendar.vue'
export { default as IconStats } from './IconStats.vue'
export { default as IconHeartStatic } from './IconHeartStatic.vue'
